# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.0-next.1"
tag_format = "v$major.$minor.$patch-$prerelease.$devrelease"
gpg_sign = true
update_changelog_on_bump = true
changelog_incremental = true
