branches:
  - v[0-9]+.[0-9]+.[0-9]+
  - main
  - next
  - next-major
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
    - '@semantic-release/commit-analyzer'
    - '@semantic-release/release-notes-generator'
    - '@semantic-release/github'
    - - '@semantic-release/exec'
      - verifyConditionsCmd: "~/.cargo/bin/semantic-release-cargo verify-conditions"
        prepareCmd: "~/.cargo/bin/semantic-release-cargo prepare ${nextRelease.version}"
        publishCmd: "~/.cargo/bin/semantic-release-cargo publish"
    - - '@semantic-release/git'
      - assets:
          - Cargo.toml
          - Cargo.lock
          - CHANGELOG.md
        message: "chore(release): ${nextRelease.version} [skip ci]"

generateNotes:
  - path: "@semantic-release/release-notes-generator"
    preset: "conventionalcommits"
