---
# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0
extends: default
rules:
    # 80 chars should be enough, but don't fail if a line is longer
    line-length:
        max: 150
        level: warning
    truthy:
        check-keys: false
    indentation:
        spaces: 4
        indent-sequences: true
    comments:
        min-spaces-from-content: 1
