---
# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT
version: 2.1
jobs:
    test-rust:
        docker:
            - image: cimg/rust:1.79
        steps:
            - checkout
            - restore_cache:
                key: cargo-{{ checksum "Cargo.lock" }}
            - run:
                command: cargo test
            - save_cache:
                key: cargo-{{ checksum "Cargo.lock" }}
                paths:
                    - ~/.cargo
workflows:
    build-and-test:
        jobs:
            - test-rust
