# SPDX-FileCopyrightText: 2023 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

[book]
authors = ["Ali Sajid Imami"]
language = "en"
multilingual = false
src = "src"
title = "Amino Acid Properties Server"
