# SPDX-FileCopyrightText: 2023 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Security Audit
on:
    schedule:
        - cron: 0 0 1,15 * *
    push:
        branches:
            - "*"
        paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'
    workflow_dispatch:

permissions:
    contents: read

jobs:
    security_audit:
        if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
        runs-on: ubuntu-latest
        permissions:
            issues: write
            checks: write
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
              with:
                egress-policy: audit

            - name: Checkout
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

            - uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
