# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Continuous integration
on:
    push:
    pull_request:
        branches:
            - main
        types:
            - closed
    workflow_dispatch:
concurrency:
    group: ${{github.event.ref}}
    cancel-in-progress: true
env:
    GIST_KEY: 625c1d8a63a7cbb926f8828d97d850b1 # pragma: allowlist secret
    RUST_BACKTRACE: 1
    MINIMUM_WAIT: 3
    MAXIMUM_WAIT: 10
jobs:
    check_changed_dirs:
      runs-on: ubuntu-latest
      outputs:
        source_changed: ${{steps.changed_dirs.outputs.source}}
        book_changed: ${{steps.changed_dirs.outputs.book}}
      steps:
        - name: Harden Runner
          uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
          with:
            egress-policy: audit

        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        - name: Check changed directories
          id: changed_dirs
          uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
          with:
            base: ${{ github.ref }}
            filters: |
              source:
                - "src/**/*"
                - "tests/**/*"
                - "examples/**/*"
                - "Cargo.toml"
                - "Cargo.lock"
              book:
                - "guide/src/*.md"
                - "guide/book.toml"
    ci:
        runs-on: ${{matrix.os}}-latest
        needs: [check_changed_dirs]
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
        outputs:
            result: ${{steps.result.outputs.result}}
        strategy:
            fail-fast: false
            matrix:
                rust:
                    - stable
                    - beta
                    - nightly
                    - 1.78.0 # MSRV
                os:
                    - ubuntu
                include:
                    - os: ubuntu
                      logo: ubuntu
                    - rust: 1.78.0 # MSRV
                      label: msrv
                    - rust: stable
                      label: stable
                    - rust: beta
                      label: beta
                    - rust: nightly
                      label: nightly
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - name: Install Rust
              if: ${{ needs.check_changed_dirs.outputs.source_changed == 'true' }}
              uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # master
              with:
                toolchain: ${{matrix.rust}}
                components: rustfmt, clippy
            - name: Install nightly Rust
              if: ${{ needs.check_changed_dirs.outputs.source_changed == 'true' }}
              uses: dtolnay/rust-toolchain@83bdede770b06329615974cf8c786f845d824dfb # nightly
              with:
                toolchain: nightly
                components: rustfmt, clippy
            - name: Cache dependencies
              if: ${{ needs.check_changed_dirs.outputs.source_changed == 'true' }}
              uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
            - name: Cargo Build
              if: ${{ needs.check_changed_dirs.outputs.source_changed == 'true' }}
              run: cargo build --verbose
            - name: Cargo Test
              if: ${{ needs.check_changed_dirs.outputs.source_changed == 'true' }}
              run: cargo test
            - name: Cargo Format
              if: ${{ needs.check_changed_dirs.outputs.source_changed == 'true' }}
              run: cargo +nightly fmt --all -- --check
            - name: Cargo Lint
              if: ${{ needs.check_changed_dirs.outputs.source_changed == 'true' }}
              run: cargo clippy -- -D warnings
            - name: Wait before badge creation
              if: ${{ needs.check_changed_dirs.outputs.source_changed == 'true' }}
              uses: AliSajid/random-wait-action@d75d5227161d2bde73ae3c4b830e38a886de19fd # v2.7.0
              with:
                minimum: ${{env.MINIMUM_WAIT}}
                maximum: ${{env.MAXIMUM_WAIT}}
            - name: Create Awesome Badge - Success
              uses: schneegans/dynamic-badges-action@e9a478b16159b4d31420099ba146cdc50f134483 # v1.7.0
              if: success()
              with:
                auth: ${{secrets.GIST_SECRET}}
                gistID: ${{env.GIST_KEY}}
                filename: ${{matrix.os}}-${{matrix.label}}.json
                label: Build
                namedLogo: ${{matrix.logo}}
                message: Succeeded
                color: green
            - name: Create Awesome Badge - Failure
              uses: schneegans/dynamic-badges-action@e9a478b16159b4d31420099ba146cdc50f134483 # v1.7.0
              if: failure()
              with:
                auth: ${{secrets.GIST_SECRET}}
                gistID: ${{env.GIST_KEY}}
                filename: ${{matrix.os}}-${{matrix.label}}.json
                namedLogo: ${{matrix.logo}}
                label: Build
                message: Failed
                isError: true
            - name: Set Result
              if: always()
              id: result
              run: echo "result=${{job.status}}" >> "$GITHUB_OUTPUT"
    generate_code_coverage:
        uses: ./.github/workflows/code_coverage.yaml
        needs: [ci, check_changed_dirs]
        if: ${{needs.check_changed_dirs.outputs.source_changed == 'true'}}
        secrets: inherit # pragma: allowlist secret
    generate_mdbook:
        uses: ./.github/workflows/deploy_mdbook.yaml
        needs: [check_changed_dirs]
        if: ${{needs.check_changed_dirs.outputs.book_changed == 'true'}}
        secrets: inherit # pragma: allowlist secret
    get-next-version:
        uses: ./.github/workflows/get_next_version.yaml
        needs: [ci, check_changed_dirs]
        if: ${{needs.ci.outputs.result == 'success'}}
        secrets: inherit # pragma: allowlist secret
    semantic-release:
        needs: [ci, get-next-version]
        if: ${{needs.get-next-version.outputs.new-release-published == 'true'}}
        uses: ./.github/workflows/release.yaml
        secrets: inherit # pragma: allowlist secret
    shuttle-deploy:
        needs: [ci, get-next-version, semantic-release]
        if: ${{needs.get-next-version.outputs.new-release-published == 'true' && github.ref == 'refs/heads/main'}}
        uses: ./.github/workflows/shuttle_deploy.yaml
        secrets: inherit # pragma: allowlist secret
    build-container:
      permissions:
        id-token: write
        packages: write
      needs: [ci]
      uses: ./.github/workflows/build_container.yaml
      secrets: inherit # pragma: allowlist secret
