---
name: Continuous integration
on:
    push:
    pull_request:
        branches:
            - main
        types:
            - closed
    workflow_dispatch:
concurrency:
    group: ${{github.event.ref}}
    cancel-in-progress: true
env:
    GIST_KEY: 625c1d8a63a7cbb926f8828d97d850b1 # pragma: allowlist secret
    RUST_BACKTRACE: 1
    MINIMUM_WAIT: 3
    MAXIMUM_WAIT: 10
jobs:
    ci:
        runs-on: ${{matrix.os}}-latest
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
        outputs:
            result: ${{steps.result.outputs.result}}
        strategy:
            fail-fast: false
            matrix:
                rust:
                    - stable
                    - beta
                    - nightly
                    - 1.75.0 # MSRV
                os:
                    - windows
                    - ubuntu
                    - macos
                include:
                    - os: windows
                      logo: windows
                    - os: ubuntu
                      logo: ubuntu
                    - os: macos
                      logo: apple
                    - rust: 1.75.0 # MSRV
                      label: msrv
                    - rust: stable
                      label: stable
                    - rust: beta
                      label: beta
                    - rust: nightly
                      label: nightly
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            - name: Install Rust
              uses: dtolnay/rust-toolchain@master
              with:
                toolchain: ${{matrix.rust}}
                components: rustfmt, clippy
            - name: Install nightly Rust
              uses: dtolnay/rust-toolchain@nightly
              with:
                toolchain: nightly
                components: rustfmt, clippy
            - name: Cache dependencies
              uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
            - name: Cargo Build
              run: cargo build --verbose
            - name: Cargo Test
              run: cargo test
            - name: Cargo Format
              run: cargo +nightly fmt --all -- --check
            - name: Cargo Lint
              run: cargo clippy -- -D warnings
            - name: Wait before badge creation
              uses: AliSajid/random-wait-action@01b537571b90fecf98521ac9dbd3054d34dd5819 # v2.2.0
              with:
                minimum: ${{env.MINIMUM_WAIT}}
                maximum: ${{env.MAXIMUM_WAIT}}
            - name: Create Awesome Badge - Success
              uses: schneegans/dynamic-badges-action@e9a478b16159b4d31420099ba146cdc50f134483 # v1.7.0
              if: success()
              with:
                auth: ${{secrets.GIST_SECRET}}
                gistID: ${{env.GIST_KEY}}
                filename: ${{matrix.os}}-${{matrix.label}}.json
                label: Build
                namedLogo: ${{matrix.logo}}
                message: Succeeded
                color: green
            - name: Create Awesome Badge - Failure
              uses: schneegans/dynamic-badges-action@e9a478b16159b4d31420099ba146cdc50f134483 # v1.7.0
              if: failure()
              with:
                auth: ${{secrets.GIST_SECRET}}
                gistID: ${{env.GIST_KEY}}
                filename: ${{matrix.os}}-${{matrix.label}}.json
                namedLogo: ${{matrix.logo}}
                label: Build
                message: Failed
                isError: true
            - name: Set Result
              if: always()
              id: result
              run: echo "result=${{job.status}}" >> "$GITHUB_OUTPUT"
    generate_code_coverage:
        uses: ./.github/workflows/code_coverage.yaml
        needs: [ci]
        secrets: inherit # pragma: allowlist secret
    generate_mdbook:
        uses: ./.github/workflows/deploy_mdbook.yaml
        needs: [ci]
        secrets: inherit # pragma: allowlist secret
    get-next-version:
        uses: ./.github/workflows/get_next_version.yaml
        needs: [ci]
        secrets: inherit # pragma: allowlist secret
    semantic-release:
        needs: [ci, get-next-version]
        if: ${{needs.get-next-version.outputs.new-release-published == 'true'}}
        uses: ./.github/workflows/release.yaml
        secrets: inherit # pragma: allowlist secret
