# SPDX-FileCopyrightText: 2023 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Code Coverage
on:
    workflow_call:

jobs:
    test:
        name: Generate Coverage
        runs-on: ubuntu-latest
        container:
            image: xd009642/tarpaulin:develop-nightly@sha256:a73a33fc46b310892989ee6f04f61b21f92f0fde7bf550138bbd7bc79a35b3e3
            options: --security-opt seccomp=unconfined
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
              with:
                egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

            - uses: dtolnay/rust-toolchain@0f44b27771c32bda9f458f75a1e241b09791b331 # nightly
              with:
                toolchain: nightly
                components: llvm-tools-preview

            - uses: taiki-e/install-action@0be4756f42223b67aa4b7df5effad59010cbf4b9 # v2.62.51
              with:
                tool: cargo-llvm-cov,nextest

            - name: Collect coverage data (including doctests)
              run: |
                cargo llvm-cov --no-report nextest --config-file nextest.toml
                cargo llvm-cov --no-report --doc
                cargo llvm-cov report --doctests --lcov --output-path lcov.info

            - name: Upload to codecov.io
              uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
              with:
                file: lcov.info
                token: ${{ secrets.CODECOV_TOKEN }}
                verbose: true
                working-directory: .
