# SPDX-FileCopyrightText: 2023 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Code Coverage
on:
    workflow_call:

jobs:
    test:
        name: Generate Coverage
        runs-on: ubuntu-latest
        container:
            image: xd009642/tarpaulin:develop-nightly@sha256:d4c6e0d3dd12ba8dc01fbfb5789045dfebb042eda90fc44b429105d395233077
            options: --security-opt seccomp=unconfined
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
              with:
                egress-policy: audit

            - name: Checkout repository
              uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

            - uses: dtolnay/rust-toolchain@0b1efabc08b657293548b77fb76cc02d26091c7e # nightly
              with:
                toolchain: nightly
                components: llvm-tools-preview

            - uses: taiki-e/install-action@1ee706eb04986370fc60419ba172594c51067f29 # v2.62.58
              with:
                tool: cargo-llvm-cov,nextest

            - name: Collect coverage data (including doctests)
              run: |
                cargo llvm-cov --no-report nextest --config-file nextest.toml
                cargo llvm-cov --no-report --doc
                cargo llvm-cov report --doctests --lcov --output-path lcov.info

            - name: Upload to codecov.io
              uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
              with:
                file: lcov.info
                token: ${{ secrets.CODECOV_TOKEN }}
                verbose: true
                working-directory: .
