# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
on:
    workflow_call:

name: Semantic Release
env:
    RUST_BACKTRACE: 1
    SEMREL_RUST_VERSION: 2.3.71
concurrency:
    group: ${{ github.event.ref }}
jobs:
    build_application:
        name: Build CLI ${{ matrix.build.target }}
        runs-on: ${{ matrix.build.os }}
        env:
            CARGO: cargo
        strategy:
            matrix:
                bin:
                    - aaprop
                build:
                    # alphabatized by target
                    - os: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                      cross: true
                    - os: ubuntu-latest
                      target: aarch64-unknown-linux-musl
                      cross: true
                    - os: ubuntu-latest
                      target: i686-unknown-linux-gnu
                      cross: true
                    - os: ubuntu-latest
                      target: i686-unknown-linux-musl
                      cross: true
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      cross: false
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-musl
                      cross: false
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - name: Install tree
              if: runner.os == 'Linux'
              run: sudo apt install tree
            - name: Install build inputs
              if: runner.os == 'Linux' && !matrix.build.cross
              run: sudo apt install musl-tools mingw-w64
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a # master
              id: rust-toolchain
              with:
                toolchain: stable
                target: ${{ matrix.build.target }}
            - name: Cache dependencies
              uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
            - name: Install cross
              uses: taiki-e/install-action@86ec8296ca78c5cfba526854b020d4e58cf41e67 # v2.44.51
              with:
                tool: cross
            - name: Configure cross
              if: matrix.build.cross
              run: echo "CARGO=cross" >> "$GITHUB_ENV"
            - name: Compile release binary
              run: ${{ env.CARGO }} build --bin ${{ matrix.bin }} --release --target ${{ matrix.build.target }} --verbose
            - name: Show generated binary
              if: runner.os == 'Linux'
              run: tree target/
            - name: Create release archive - windows
              if: matrix.build.target == 'x86_64-pc-windows-gnu' || matrix.build.target == 'i686-pc-windows-gnu'
              run: |
                mkdir dist
                cp target/${{ matrix.build.target }}/release/${{ matrix.bin }}.exe dist/${{ matrix.bin }}-${{ matrix.build.target }}
            - name: Create release archive - non-windows
              if: matrix.build.target != 'x86_64-pc-windows-gnu' && matrix.build.target != 'i686-pc-windows-gnu'
              run: |
                mkdir dist
                cp target/${{ matrix.build.target }}/release/${{ matrix.bin }} dist/${{ matrix.bin }}-${{ matrix.build.target }}
            - name: Create binary checksum
              run: |
                shasum --algorithm 256 \
                --binary ${{ matrix.bin }}-${{ matrix.build.target }} | tee ${{ matrix.bin }}-${{ matrix.build.target }}-SHA256SUM.txt
              working-directory: ./dist
            - name: Upload release artifacts
              uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
              with:
                name: ${{ matrix.build.target }}
                path: |
                    dist/${{ matrix.bin }}-${{ matrix.build.target }}
                    dist/${{ matrix.bin }}-${{ matrix.build.target }}-SHA256SUM.txt
                if-no-files-found: error
                retention-days: 1
    release:
        name: Semantic Release
        runs-on: ubuntu-latest
        needs: build_application
        outputs:
            new_release_version: ${{steps.semantic.outputs.new_release_version}}
            new_release_published: ${{steps.semantic.outputs.new_release_published}}
            new_release_notes: ${{steps.semantic.outputs.new_release_notes}}
            new_release_channel: ${{steps.semantic.outputs.new_release_channel}}
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                fetch-depth: 0
                persist-credentials: false
            - name: Import GPG key
              uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
              with:
                gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}
                fingerprint: ${{ secrets.GPG_SUBKEY_FINGERPRINT }}
                trust_level: 5
                git_user_signingkey: true
                git_commit_gpgsign: true
                git_tag_gpgsign: false
                git_committer_name: ${{ vars.GIT_AUTHOR_NAME }}
                git_committer_email: ${{ vars.GIT_AUTHOR_EMAIL }}
            - name: Test GPG Key Import
              run: gpg --list-keys --keyid-format LONG
            - name: Install dependencies
              run: sudo apt install tree
            - name: Install semantic-release-cargo
              uses: taiki-e/install-action@86ec8296ca78c5cfba526854b020d4e58cf41e67 # v2.44.51
              with:
                tool: semantic-release-cargo@${{env.SEMREL_RUST_VERSION}}
            - name: Download release artifacts
              uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
              with:
                path: artifacts
            - name: ls artifacts
              run: tree ./artifacts
            - name: Prepare GitHub Release artifacts
              run: ./scripts/build.sh
            - name: Install Conventional Commit preset
              run: npm install conventional-changelog-conventionalcommits
            - name: Semantic Release
              uses: cycjimmy/semantic-release-action@b1b432f13acb7768e0c8efdec416d363a57546f2 # v4.1.1
              id: semantic
              with:
                semantic_version: 24.0.0
                extra_plugins: |
                    @semantic-release/exec@6
                    @semantic-release/git@10
              env:
                GITHUB_TOKEN: ${{secrets.ACTIONS_PAT_GITHUB}}
                CARGO_REGISTRY_TOKEN: ${{secrets.SEMREL_CRATES_IO}}
                GIT_AUTHOR_NAME: ${{vars.GIT_AUTHOR_NAME}}
                GIT_AUTHOR_EMAIL: ${{vars.GIT_AUTHOR_EMAIL}}
                GIT_COMMITTER_NAME: ${{vars.GIT_AUTHOR_NAME}}
                GIT_COMMITTER_EMAIL: ${{vars.GIT_AUTHOR_EMAIL}}
