# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Deploy to Shuttle
on:
    workflow_call:

jobs:
    shuttle-deployment:
        name: Shuttle Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
              with:
                egress-policy: audit

            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - uses: shuttle-hq/deploy-action@1872b44280192f6f5d924b784e2b307d070e2929 # main
              with:
                deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
