# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Deploy to Shuttle
on:
    workflow_call:

jobs:
    shuttle-deployment:
        name: Shuttle Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
            - uses: shuttle-hq/deploy-action@main
              with:
                deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
