# SPDX-FileCopyrightText: 2023 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Deploy to Shuttle
on:
    workflow_call:

jobs:
    shuttle-deployment:
        name: Shuttle Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
              with:
                egress-policy: audit

            - name: Checkout
              uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

            - uses: shuttle-hq/deploy-action@e1c2ff9b0d68adb0b2cfb35e29edfb335b854e41 # main
              with:
                deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
