# SPDX-FileCopyrightText: 2023 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Deploy to Shuttle
on:
    workflow_call:

jobs:
    shuttle-deployment:
        name: Shuttle Deployment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            - uses: shuttle-hq/deploy-action@main
              with:
                deploy-key: ${{ secrets.SHUTTLE_DEPLOY_KEY }}
