# SPDX-FileCopyrightText: 2023 - 2025 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: Sonarcloud Analysis
on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonarcloud:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for SonarSource/sonarcloud-github-action to determine which PR to decorate
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ba3875ecf642b2129de2b589510c81a8b53dbf4e # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
